# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
