# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20171107_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='link',
        ),
    ]
