# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_remove_skill_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
