# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20171108_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
